var value ;

try{
    console.log(value.length);
}catch(err){
    console.log('err',err);
}finally{

}

throw "에러발생";
console.log('실행')
